# Clang with transactional memory
# TMBUILD ?= clangtm

# ======== Defines ========
CC = clang
CPPFLAGS += -DNDEBUG
CPPFLAGS += -I../lib -I../common/$(TMBUILD)
CPPFLAGS += -I../../../libitm/clang
CFLAGS   += -Wall -Wextra
CFLAGS   += -fgnu-tm
CFLAGS   += -O3 -ggdb

LD       := clang++
LDFLAGS  += -lpthread
LDFLAGS  += -L../../../libitm/clang -litm
LIBDEPS  += ../../../libitm/clang/libitm.a

include ../common/Makefile.common
