# GCC with transactional memory
# TMBUILD ?= gcctm

# ======== Defines ========
CC       := gcc
CPPFLAGS += -DNDEBUG
CPPFLAGS += -I../lib -I../common/$(TMBUILD)
CPPFLAGS += -I../../../libitm/gcc
CFLAGS   += -Wall -Wextra
CFLAGS   += -fgnu-tm
CFLAGS   += -O3 -fno-tree-vectorize -ggdb

LD       := g++
LDFLAGS  += -lpthread
LDFLAGS  += -L../../../libitm/gcc -litm
LIBDEPS  +=  ../../../libitm/gcc/libitm.a

include ../common/Makefile.common
