# GCC with transactional memory
# TMBUILD ?= gcctm

# ======== Defines ========
CC       := gcc
CPPFLAGS += -DNDEBUG -D_GNU_SOURCE
CPPFLAGS += -I../lib -I../common/$(TMBUILD)
CPPFLAGS += -I../../../libitm/gcc
CFLAGS   += -Wall -Wextra
CFLAGS   += -fgnu-tm
CFLAGS   += -O3 -ggdb

LD       := $(CC)
LDFLAGS  += -lpthread
LDFLAGS  += -L../../../libitm/gcc -litm
LIBDEPS  += 

include ../common/Makefile.common
