# TMBUILD = gcctm-prof
# ======== Defines ========
CC       := gcc
CPPFLAGS += -DNDEBUG
CPPFLAGS += -I../common/$(TMBUILD)
CFLAGS   += -Wall -Wextra
CFLAGS   += -O3 -g -fgnu-tm

LD       := g++
LDFLAGS  += -lpthread

LIBDIR    = ../../../libitm/gcc-prof
CPPFLAGS += -I$(LIBDIR)
LDFLAGS  += -L$(LIBDIR) -litm
LDFLAGS  += -lbfd -lelf -lz -liberty
TMLIB    += $(LIBDIR)/libitm.a

include ../common/Makefile.common
