# TMBUILD = rtm
# ======== Defines ========
#CC       := gcc
CPPFLAGS += -DNDEBUG
CPPFLAGS += -I../common/$(TMBUILD) -DRTM
CFLAGS   += -Wall -Wextra
CFLAGS   += -O3 -mrtm

LD       := $(CC)
LDFLAGS  += -lpthread -ldl

LIBDIR   = ../../../htm
CPPFLAGS += -I$(LIBDIR)
LDFLAGS  += -L$(LIBDIR) -lhtm
TMLIB     = $(LIBDIR)/libhtm.a

include ../common/Makefile.common
