# TMBUILD = rtm
# ======== Defines ========
CC       := gcc-4.8.3
CPPFLAGS += -DNDEBUG
CPPFLAGS += -I../common/$(TMBUILD) -DRTM
CFLAGS   += -Wall -Wextra
CFLAGS   += -O3 -mrtm

LD       := gcc-4.8.3
LDFLAGS  += -lpthread

LIBDIR   = ../../../tsx/rtm
CPPFLAGS += -I$(LIBDIR)
LDFLAGS  += -L$(LIBDIR) -lrtm -mrtm
TMLIB     = $(LIBDIR)/librtm.a

include ../common/Makefile.common
