# tsx-rtm build
#TMBUILD ?= tsx-rtm

# ======== Defines ========
CC       := gcc
#CPPFLAGS += -DNDEBUG
CPPFLAGS += -I../lib -I../common/$(TMBUILD)
CFLAGS   += -Wall -Wextra
CFLAGS   += -O3

LD       := gcc
LDFLAGS  += -lpthread

TMLIBDIR ?= ../../../tsx/rtm
CPPFLAGS += -I$(TMLIBDIR)
LDFLAGS  += -L$(TMLIBDIR) -lrtm
LIBDEPS  += $(TMLIBDIR)/librtm.a

include ../common/Makefile.common
