#!/usr/bin/make

target = librtm.a

DEFINES += -DRTM_ABORT_DEBUG

# DEFINES += -DRTM_CM_SPINLOCK

# DEFINES += -DRTM_CM_TRYLOCK

# DEFINES += -DRTM_CM_AUXLOCK -DRTM_CM_SPINLOCK

# DEFINES += -DRTM_CM_BACKOFF -DRTM_CM_SPINLOCK

CFLAGS += -O3 -Wall -I. -I../ -I../hle -mrtm $(DEFINES)

all: $(target)

librtm.a: rtm.o
	$(AR) cr $@ $<

rtm.o: rtm.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	$(RM) *.a *.o
