#!/usr/bin/make

target = librtm.a

ifdef THRESHOLD
  DEFINES += -DRTM_MAX_RETRIES=$(THRESHOLD)
endif

# DEFINES += -DSIMPLE_LOCK

# DEFINES += -DHLE_LOCK

# DEFINES += -DRTM_CM_GLOCK

# DEFINES += -DRTM_CM_AUXLOCK

# DEFINES += -DRTM_CM_BACKOFF

# DEFINES += -DRTM_CM_DIEGUES -DFALLBACK_PROB=10

CFLAGS += -O3 -Wall -I. -I../ -I../hle -mrtm $(DEFINES)

all: $(target)

librtm.a: rtm.o
	$(AR) cr $@ $<

rtm.o: rtm.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	$(RM) *.a *.o
