# TMBUILD ?= proftm
CC       := gcc
CPPFLAGS += -DNDEBUG
CPPFLAGS += -I../lib -I../common/$(TMBUILD)
CPPFLAGS += -I../../../libitm/gcc-prof
CFLAGS   += -Wall -Wextra
CFLAGS   += -fgnu-tm
CFLAGS   += -O3 -g

LD       := g++
LDFLAGS  += -lpthread -lbfd -lelf -lz -liberty
LDFLAGS  += -L../../../libitm/gcc-prof -litm
LIBDEPS  += ../../../libitm/gcc-prof/libitm.a

include ../common/Makefile.common
