#!/bin/bash

source $PWD/scripts/scripts.cfg
[ $? != 0 ] && echo -e "\nerror: running scripts from wrong directory!" && exit -1

function usage {
	
	echo $0' [-d <tinySTM DESIGN>]  [-m <tinySTM CM>] [-a <stamp app>] [-D <RTM CM>] [-l <TSX lock>]'
	echo -e '\t[-t <n. threads>] [-n <nb executions>] [-b <build>] [-M <memalloc>] [-g <governor>]'

	echo
	echo '-d <tinySTM DESIGN>'
	echo 'ETL | CTL | WT'
	echo 'default = ALL'

	echo
	echo '-m <tinySTM CM>'
	echo 'SUICIDE | BACKOFF | DELAY'
	echo 'default = ALL'
	
	echo
	echo '-D <RTM CM>'
	echo 'glock | auxlock | backoff | diegues'
	echo 'default = ALL'
	
	echo
	echo '-l <TSX lock>'
	echo 'simple_lock | hle_lock'
	echo 'default = ALL'

	echo
	echo '-a <stamp app>'
	echo 'bayes | genome | intruder | kmeans | labyrinth | ssca2 | vacation | yada'
	echo 'default = ALL'

	echo
	echo '-b <build>'
	echo 'tinystm | seq | lock | hle | rtm | norec'
	echo 'default = ALL'
	
	echo
	echo '-M <memalloc>'
	echo 'ptmalloc | tcmalloc | hoard | tbbmalloc'
	echo 'default = ptmalloc'
	
	echo
	echo '-g <governor>'
	echo 'powersave | conservative | ondemand | userspace | performance'
	echo 'default = ondemand'

	echo
	echo '-t <n. threads>'
	echo '1 | 2 | 4 | etc... | "1 2 4 8" | "4 8 16" | etc...'
	echo 'default = "1 2 3 4"'

	echo
	echo '-n <n. executions>'
	echo 'default = 20'
}

function setGovernor {
	
	governor=$1
	for processor in $(cat /proc/cpuinfo | grep processor | awk '{print $3}');
	do
		sudo cpufreq-set -c $processor -g $governor
		test $governor == 'userspace' && sudo cpufreq-set -c $processor -f ${!governor}
	done
}

function restoreGovernor {

	governor='ondemand'
	for processor in $(cat /proc/cpuinfo | grep processor | awk '{print $3}');
	do
		sudo cpufreq-set -c $processor -g $governor
	done
}

function execute {

	test -e $LOGDIR || mkdir -p $LOGDIR
	
	test -z "$_BUILDS"           && _BUILDS=$BUILDS
	test -z "$_NEXEC"            && _NEXEC=$NEXEC
	test -z "$_NTHREADS"         && _NTHREADS=$NTHREADS
	test -z "$_MEM_ALLOCS"       && _MEMALLOCS='ptmalloc'
	test "$_MEM_ALLOCS" == "ALL" && _MEMALLOCS=$MEM_ALLOCS
	test -z "$_GOVERNORS"        && _GOVERNORS='ondemand'
	test "$_GOVERNORS" == "ALL"  && _GOVERNORS=$GOVERNORS
	test -z "$_tinySTM_DESIGNS"  && _tinySTM_DESIGNS=$tinySTM_DESIGNS
	test -z "$_tinySTM_CMS"      && _tinySTM_CMS=$tinySTM_CMS
	test -z "$_STAMP_APPS"       && _STAMP_APPS=$STAMP_APPS
	test -z "$_rtm_CMS"          && _rtm_CMS=$rtm_CMS
	test -z "$_tsx_LOCKS"        && _tsx_LOCKS=$tsx_LOCKS
	
	echo 'starting execution...'

	for app in ${_STAMP_APPS}; do
		eval exec_flags=\$EXEC_FLAG_$app
		for build in $_BUILDS; do
			SUFFIXES=$build
			test $build == 'tinystm' && \
				SUFFIXES="$(eval echo -n $build-{${_tinySTM_DESIGNS// /,}}-{${_tinySTM_CMS// /,}} | sed 's|{||g;s|}||g')"
			test $build == 'rtm' && \
				SUFFIXES="$(eval echo -n $build-{${_rtm_CMS// /,}}-{${_tsx_LOCKS// /,}} | sed 's|{||g;s|}||g')"
			NUMTHREADS=$_NTHREADS
			test $build == "seq" && NUMTHREADS='1'
			SUFFIXES="$(eval echo -n {${SUFFIXES// /,}}-{${_GOVERNORS// /,}} | sed 's|{||g;s|}||g')"
			for suffix in $SUFFIXES; do
				regex='-([a-z]+)$' # regular expression to get governor from suffix variable
				[[ $suffix =~ $regex ]] && governor=${BASH_REMATCH[1]} #&& setGovernor $governor
				appRunPath="$STAMP/$build/$app/$app-$(sed 's/-[a-z]\+$//' <<< $suffix)" # remove governor from suffix
				for memalloc in $_MEMALLOCS; do
					for t in $NUMTHREADS; do
						outputLog="$LOGDIR/$app-$suffix-$memalloc-$t.log"
						rm -f $outputLog
						for j in $(seq 1 ${_NEXEC}); do
							echo "execution $j: $appRunPath ${exec_flags}$t ($memalloc) ($governor)"	
							sudo LD_PRELOAD=${!memalloc} STM_CONFIG=${!build} ${appRunPath} ${exec_flags}$t  >> $outputLog
						done # FOR EACH EXECUTION
					done # FOR EACH NUMBER OF THREADS
				done # FOR EACH MEMORY ALLOCATOR
				#restoreGovernor # reset system governor to ondemand
			done # FOR EACH SUFFIX
		done # FOR EACH BUILD
	done # FOR EACH APPS

	echo 'execution finished.'
}

while getopts "b:d:m:D:l:a:t:n:g:M:h" opt;
do
	case $opt in
		b) _BUILDS=$OPTARG ;;
		d) _tinySTM_DESIGNS=$OPTARG ;;
		m) _tinySTM_CMS=$OPTARG ;;
		D) _rtm_CMS=$OPTARG ;;
		l) _tsx_LOCKS=$OPTARG ;;
		a) _STAMP_APPS=$OPTARG ;;
		t) _NTHREADS=$OPTARG ;;
		n) _NEXEC=$OPTARG ;;
		g) _GOVERNORS=$OPTARG ;;
		M) _MEMALLOCS=$OPTARG ;;
		h) usage && exit -1 ;;
		\?) echo $0" : error - invalid option -- $OPTARG"
			exit 1
	esac
done

execute
