# TMBUILD = seq
# ======== Defines ========
CC       := gcc
CPPFLAGS += -DNDEBUG
CPPFLAGS += -I$(TMBUILD)
CFLAGS   += -Wall -Wextra
CFLAGS   += -O3

LD       := gcc
LDFLAGS  += -lpthread

TMLIB    = 
