
ARCH = $(shell uname -m)

ifeq ($(ARCH), x86_64)
  MSR = ../../../msr

  CPPFLAGS += -I$(MSR)
  LDFLAGS  += -L$(MSR) -lmsr -lm

  ifdef PROFILING
    CPPFLAGS += -DPROFILING=$(PROFILING)
  endif
endif

CPPFLAGS += -D_GNU_SOURCE
